-- Initial schema for tj-shop v1.
--
-- Tables:
--   stores           — TJ physical stores (PB, La Jolla, ...)
--   categories       — TJ's national category tree (flat, no nesting in v1)
--   products         — TJ's national catalog (name/sku/image/size/category)
--   store_products   — per-store facts: price, availability, user notes
--
-- All PKs are UUIDs generated by the application (uuid v7).

create or replace function set_updated_at() returns trigger as $$
begin
    new.updated_at = now();
    return new;
end;
$$ language plpgsql;

create table stores (
    id         uuid primary key,
    tj_code    text unique not null,
    name       text not null,
    city       text,
    state      text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger trg_stores_updated_at
    before update on stores
    for each row execute function set_updated_at();

create table categories (
    id         uuid primary key,
    tj_id      text unique not null,
    name       text not null,
    position   integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create trigger trg_categories_updated_at
    before update on categories
    for each row execute function set_updated_at();

create table products (
    id          uuid primary key,
    sku         text unique,
    name        text not null,
    size        text,
    image_url   text,
    category_id uuid references categories(id),
    is_manual   boolean not null default false,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

create index idx_products_category on products(category_id);

create trigger trg_products_updated_at
    before update on products
    for each row execute function set_updated_at();

create table store_products (
    id           uuid primary key,
    store_id     uuid not null references stores(id) on delete cascade,
    product_id   uuid not null references products(id) on delete cascade,
    price        numeric(10, 2),
    available    boolean not null default true,
    notes        text,
    last_seen_at timestamptz,
    created_at   timestamptz not null default now(),
    updated_at   timestamptz not null default now(),
    unique (store_id, product_id)
);

create trigger trg_store_products_updated_at
    before update on store_products
    for each row execute function set_updated_at();
